### ISSUE TITLE
[Bug] Failure to unmarshal some transactions from API

### ISSUE THREAD

**Issue by peterargue** [aptos-labs/aptos-go-sdk#63]
# 🐛 Bug Description

When querying transactions from the API, I occasionally get json unmarshal errors using the SDK.

In the reproduction case below, it seems the issue is related to this case:
```json
{
  "version": "996270881",
  ...
  "changes": [
    {
      "address": "0x307401f7dd9ca5371ed820070dabaff6cf2196b500c0e359c0e388897987ca6a",
      "state_key_hash": "0x3775f4dbd6900b26cf6c833b112fdfda084f84ef4e562678ca6b54a4791063fd",
      "resource": "0x1::object::ObjectGroup",
      "type": "delete_resource"
    },
    ...
  ],
  ...
}
```

It looks like in the type definition, `resource` is defined as a `MoveResource`, but is returned as a string in this case
https://github.com/aptos-labs/aptos-go-sdk/blob/91228a383a9e59b313e9ba3886dd6c99c8a57b19/api/writeSet.go#L127-L132

## How to reproduce

**Code snippet to reproduce**
```golang
package main

import (
	"log"

	aptossdk "github.com/aptos-labs/aptos-go-sdk"
)

func main() {
	client, err := aptossdk.NewClient(aptossdk.MainnetConfig)
	if err != nil {
		log.Fatalf("error connecting to api: %v", err)
	}

	start := uint64(996270881)
	limit := uint64(1)
	_, err = client.Transactions(&start, &limit)
	if err != nil {
		log.Fatalf("err: %v", err)
	}
}
```

**Stack trace / error message**
```
get transactions api err: json: cannot unmarshal string into Go struct field inner.changes of type api.MoveResource
```

## Expected Behavior

The SDK should be able to parse all data returned from the official API

## System information

**System details:**
- Golang SDK Version: `v0.5.0`
- Golang Version: `v1.22.4`

**Comment by gregnazario** [comment]
Interesting, looks like it was improperly handled.  Will fix

**Comment by gregnazario** [comment]
For reference, you're talking about this transaction https://fullnode.mainnet.aptoslabs.com/v1/transactions/by_version/996270881
